spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nutriapp_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 12345
    driverClassname: com.mysql.cj.jdbc.Driver